# Generated by Django 4.2.7 on 2025-11-24 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_savedpaymentmethod_card_number_promousage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная'), ('auto', 'Автоматическая')], default='light', max_length=10, verbose_name='Тема')),
                ('date_format', models.CharField(choices=[('DD.MM.YYYY', 'ДД.ММ.ГГГГ'), ('YYYY-MM-DD', 'ГГГГ-ММ-ДД'), ('MM/DD/YYYY', 'ММ/ДД/ГГГГ'), ('DD MMM YYYY', 'ДД МММ ГГГГ')], default='DD.MM.YYYY', max_length=20, verbose_name='Формат даты')),
                ('number_format', models.CharField(choices=[('ru', 'Русский (1 234,56)'), ('en', 'Английский (1,234.56)'), ('space', 'С пробелами (1 234.56)')], default='ru', max_length=10, verbose_name='Формат чисел')),
                ('page_size', models.IntegerField(default=20, help_text='Количество элементов на странице', verbose_name='Размер страницы')),
                ('saved_filters', models.JSONField(blank=True, default=dict, null=True, verbose_name='Сохраненные фильтры')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
                'db_table': 'usersettings',
            },
        ),
    ]
