# Generated by Django 4.2.7 on 2025-11-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('resolved', 'Решено')], default='new', max_length=50, verbose_name='Статус'),
        ),
    ]
